### PR TITLE
Modified signature for plugin methods.

### PR DESCRIPTION
**Pull request by shosokawa**
I would like to try this plugin. Though signature for plugin method was too old to use this with phonegap3.
So I modified signatures.

### CODE REVIEW

**Comment by gregavola** [comment]
How can I add your copy to my PG3 project? 

phonegap local plugin add https://github.com/shosokawa/KeyboardToolbarRemover

Doesn't appear to work:

kipping existing file: keyboard_toolbar_remover.js

/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/plugman/src/install.js:286
            else throw err;
                       ^
Error: Uh oh!
cannot find "/Users/gregavola/Documents/Projects/utscannr/utscanner/plugins/com.chariotsolutions.cordova.plugin.keyboard_toolbar_remover/KeyboardToolbarRemover.m" ios <source-file>
    at module.exports.source-file.install (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/plugman/src/platforms/ios.js:44:48)

**Comment by shosokawa** [comment]
I didn't use phonegap command. I installed this plugin manually.

**Comment by gregavola** [comment]
How can you install this manually?

Greg

On Tue, Oct 1, 2013 at 10:10 PM, Shinichi Hosokawa <notifications@github.com

> wrote:
> 
> I didn't use phonegap command. I installed this plugin manually.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/don/KeyboardToolbarRemover/pull/5#issuecomment-25509097
> .

## 

Greg Avola
http://gregavola.me
(c) 508.596.8811

**Comment by don** [comment]
@shosokawa thanks for submitting this patch.

This was also fixed by #6. I merged the other pull request since it had the changes necessary for plugman/cli integration too.

**Comment by shosokawa** [comment]
Ok, don. That pull request was better!

**Pull request closed without merging**
